### ISSUE TITLE
Failed finding game

### ISSUE THREAD

**Issue by blankdrive** [leia-uwu/resurviv#67]
I hosted it using 
pnpm install
pnpm dev:client
and after that it hosts but for some reason I keep on getting Failed Finding Game.
please help

**Comment by lmssiehdev** [comment]
did you start the server using `dev:server`?

**Comment by spalheapp** [comment]
> Eu hospedei usando pnpm install pnpm dev:client e depois disso ele hospeda, mas por algum motivo continuo recebendo Falha ao encontrar o jogo. Por favor ajude

Simple, just use: pnpm install, pnpm -r dev.

**Comment by spalheapp** [comment]
> I hosted it using pnpm install pnpm dev:client and after that it hosts but for some reason I keep on getting Failed Finding Game. please help

Simple, just use: pnpm install, pnpm -r dev.
